### ISSUE TITLE
add link to live website in Readme.MD

### ISSUE THREAD

**Issue by doktor5000** [48klocs/Percolator#3]
Had to look in the [reddit post](https://www.reddit.com/r/DestinyTheGame/comments/5p1o02/percolator_for_all_your_weapon_selection_needs/) to find the live website https://48klocs.github.io/Percolator/ as it didn't work from a local git clone for me, would be nice if you could add that in the description, or maybe I'm totally blind and didn't see it.

And thanks for the percolator ^^

**Comment by 48klocs** [comment]
You are totes right.  I'll get that sorted.

**Comment by 48klocs** [comment]
@doktor5000 link to the live site is go.

Browsers don't love to run JavaScript from the local file system (because shrug), so you might need to spin up a local web server to test things on a local clone.  I used Fenix on my end.  You could use Python or node or whatever for something quick 'n dirty as well.
